/-
Copyright (c) 2025 Michael R. Douglas. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Bochner/Minlos Type Definitions

Local copies of type class and structure definitions from the bochner library,
so that GFF4D can state axioms using these types without importing bochner.
The bochner library (https://github.com/mrdouglasny/bochner) provides fully
proven versions of all theorems using these types.

Certificates in `certificates/import/` document the provenance of each axiom.
-/

import Mathlib.Analysis.LocallyConvex.WithSeminorms
import Mathlib.Topology.Algebra.Module.WeakDual
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure

open MeasureTheory
open scoped BigOperators

noncomputable section

/-! ### Positive Definite Functions (bochner convention)

Bochner's `IsPositiveDefinite` requires both hermitian symmetry φ(-x) = conj(φ(x))
and the standard nonneg-definite condition. This is stronger than GFF4D's
`GFF4D.IsPositiveDefinite` which only requires nonneg-definiteness. -/

/-- A function φ : α → ℂ is **positive definite** in Bochner's sense if it is
    hermitian (φ(-x) = conj(φ(x))) and nonneg-definite. -/
structure BochnerPD {α : Type*} [AddGroup α] (φ : α → ℂ) : Prop where
  hermitian : ∀ x : α, φ (-x) = starRingEnd ℂ (φ x)
  nonneg : ∀ (m : ℕ) (x : Fin m → α) (c : Fin m → ℂ),
    0 ≤ (∑ i, ∑ j, (starRingEnd ℂ) (c i) * c j * φ (x i - x j)).re

/-! ### Hilbertian Seminorms -/

/-- A seminorm is **Hilbertian** (comes from an inner product) iff it satisfies
    the parallelogram law. -/
def Seminorm.IsHilbertian {E : Type*} [AddCommGroup E] [Module ℝ E]
    (p : Seminorm ℝ E) : Prop :=
  ∀ x y : E, p (x + y) ^ 2 + p (x - y) ^ 2 = 2 * (p x ^ 2 + p y ^ 2)

/-- The inner product induced by a Hilbertian seminorm via polarization. -/
noncomputable def Seminorm.innerProd {E : Type*} [AddCommGroup E] [Module ℝ E]
    (p : Seminorm ℝ E) (x y : E) : ℝ :=
  (p (x + y) ^ 2 - p (x - y) ^ 2) / 4

/-- A finite sequence is **p-orthonormal**: ⟨eᵢ, eⱼ⟩_p = δᵢⱼ. -/
def Seminorm.IsOrthonormalSeq {E : Type*} [AddCommGroup E] [Module ℝ E]
    (p : Seminorm ℝ E) {n : ℕ} (e : Fin n → E) : Prop :=
  ∀ i j, p.innerProd (e i) (e j) = if i = j then 1 else 0

/-! ### Hilbert-Schmidt Embeddings -/

/-- The canonical inclusion Ê_p → Ê_q is **Hilbert-Schmidt**: the sum ∑ q(eₖ)²
    is uniformly bounded over all finite p-orthonormal sequences. -/
def Seminorm.IsHilbertSchmidtEmbedding {E : Type*} [AddCommGroup E] [Module ℝ E]
    (p q : Seminorm ℝ E) : Prop :=
  q ≤ p ∧
  ∃ (C : ℝ), ∀ (n : ℕ) (e : Fin n → E),
    p.IsOrthonormalSeq e →
    ∑ i, q (e i) ^ 2 ≤ C

/-! ### Nuclear Spaces (Hilbert-Schmidt characterization) -/

/-- A **nuclear space** is a locally convex space whose topology is generated by a
    countable family of Hilbertian seminorms with Hilbert-Schmidt inclusion maps.

    **Reference:** Trèves, "Topological Vector Spaces", Ch. 50, Thm 50.1;
    Gel'fand-Vilenkin Vol. 4, Ch. 3-4. -/
class IsHilbertNuclear (E : Type*) [AddCommGroup E] [Module ℝ E]
    [TopologicalSpace E] : Prop where
  nuclear_hilbert_embeddings :
    ∃ (p : ℕ → Seminorm ℝ E),
      (∀ n, (p n).IsHilbertian) ∧
      (WithSeminorms (fun n => p n)) ∧
      (∀ n, (p (n + 1)).IsHilbertSchmidtEmbedding (p n))

/-! ### Measurable Structure on WeakDual -/

variable {E : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E]

/-- Cylinder σ-algebra on WeakDual ℝ E, generated by evaluation maps.
    For separable nuclear spaces, this equals the Borel σ-algebra. -/
instance : MeasurableSpace (WeakDual ℝ E) :=
  ⨆ (f : E), (borel ℝ).comap (fun l : WeakDual ℝ E => (l : E →L[ℝ] ℝ) f)

/-- Each evaluation map `l ↦ l(f)` is measurable w.r.t. the cylinder σ-algebra. -/
lemma WeakDual.eval_measurable (f : E) :
    Measurable (fun l : WeakDual ℝ E => (l : E →L[ℝ] ℝ) f) := by
  rw [measurable_iff_comap_le]
  exact le_iSup (fun (g : E) =>
    (borel ℝ).comap (fun l : WeakDual ℝ E => (l : E →L[ℝ] ℝ) g)) f

/-! ### Minlos Theorem (axioms)

These axioms are proved in the bochner library. See `certificates/import/` for
provenance documentation. -/

set_option checkBinderAnnotations false

/-- **Minlos Theorem**: On a Hilbert-nuclear separable space E, a continuous
    positive-definite normalized functional Φ : E → ℂ is the characteristic
    functional of a unique probability measure on WeakDual ℝ E.

    **Proved in:** bochner library, Minlos/Main.lean -/
axiom minlos_theorem
  {E : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E]
  [IsTopologicalAddGroup E] [ContinuousSMul ℝ E]
  [IsHilbertNuclear E] [TopologicalSpace.SeparableSpace E] [Nonempty E]
  (Φ : E → ℂ)
  (h_continuous : Continuous Φ)
  (h_positive_definite : BochnerPD Φ)
  (h_normalized : Φ 0 = 1) :
  ∃! μ : ProbabilityMeasure (WeakDual ℝ E),
    ∀ f : E, Φ f = ∫ ω, Complex.exp (Complex.I * ((ω : E →L[ℝ] ℝ) f)) ∂μ.toMeasure

/-- **Minlos Uniqueness**: Two probability measures with the same characteristic
    functional on a nuclear space must be equal.

    **Proved in:** bochner library, Minlos/Main.lean -/
axiom minlos_uniqueness
  {E : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E]
  [IsTopologicalAddGroup E] [ContinuousSMul ℝ E]
  [IsHilbertNuclear E] [TopologicalSpace.SeparableSpace E] [Nonempty E]
  {Φ : E → ℂ} (hΦ_cont : Continuous Φ)
  (hΦ_pd : BochnerPD Φ) (hΦ_norm : Φ 0 = 1)
  {μ₁ μ₂ : ProbabilityMeasure (WeakDual ℝ E)}
  (h₁ : ∀ f : E, ∫ ω, Complex.exp (Complex.I * ((ω : E →L[ℝ] ℝ) f)) ∂μ₁.toMeasure = Φ f)
  (h₂ : ∀ f : E, ∫ ω, Complex.exp (Complex.I * ((ω : E →L[ℝ] ℝ) f)) ∂μ₂.toMeasure = Φ f) :
  μ₁ = μ₂

end
